- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - config.yaml  

  tasks:
# ---- System Peperation Tasks ----
    - name: System Preparation | Patch and update the system
      import_tasks: tasks/system-updates.yaml

    - name: System Preparation | Include system configuration tasks
      import_tasks: tasks/system-config.yaml

