# Inventory file for Ansible to manage Docker Swarm nodes
# This file defines the hosts that Ansible will manage. The hosts are grouped into 'master' and 'worker' groups.
# You must ensure that atleast one host is defined in the 'master' group and the rest in the 'worker' group.

[all]
192.168.1.150 #MLH-LAB-SWARM01
192.168.1.151 #MLH-LAB-SWARM02
192.168.1.152 #MLH-LAB-SWARM03

[master]
192.168.1.150 #MLH-LAB-SWARM01

[worker]
192.168.1.151 #MLH-LAB-SWARM02
192.168.1.152 #MLH-LAB-SWARM03